copied the code from the script

diff --git a/.github/workflows/grype.yaml b/.github/workflows/grype.yaml
--- a/.github/workflows/grype.yaml
+++ b/.github/workflows/grype.yaml
@@ -27,20 +27,31 @@ jobs:
 
       - name: Process Git Subtrees
         run: |
-          while IFS= read -r url; do
-            local_dir=$(basename "$url" .git)
+            while IFS= read -r url; do
+            # Extract the last part of the URL to use as the local directory name
+              local_dir=$(basename "$url" .git)
 
-            if [ -d "$local_dir" ]; then
-              echo "Updating subtree for URL: $url"
-              git subtree pull --prefix "$local_dir" "$url" master --squash
-            else
-              echo "Adding new subtree for URL: $url"
-              git subtree add --prefix "$local_dir" "$url" master --squash
-            fi
+              echo "Processing subtree for URL: $url"
 
-            echo "Pushing subtree changes for URL: $url"
-            git subtree push --prefix "$local_dir" "$url" master
-          done < onos_links.txt
+                # Check if the directory already exists
+                if [ -d "$local_dir" ]; then
+                    echo "Directory $local_dir already exists. Updating subtree..."
+                    git subtree pull --prefix "$local_dir" "$url" "$REMOTE_BRANCH" --squash
+                    if [ $? -ne 0 ]; then
+                        echo "Error: Failed to update subtree for URL: $url"
+                    else
+                        echo "Subtree updated successfully for URL: $url"
+                    fi
+                else
+                    echo "Adding new subtree..."
+                    git subtree add --prefix "$local_dir" "$url" "$REMOTE_BRANCH" --squash
+                    if [ $? -ne 0 ]; then
+                        echo "Error: Failed to add subtree for URL: $url"
+                    else
+                        echo "Subtree added successfully for URL: $url"
+                    fi
+                fi
+            done < onos_links.txt
     
   Grype-Scan:
     needs: sync-subtrees
