trying to di it directly in rthe workflow

diff --git a/.github/workflows/grype.yaml b/.github/workflows/grype.yaml
--- a/.github/workflows/grype.yaml
+++ b/.github/workflows/grype.yaml
@@ -6,38 +6,44 @@ on:
     branches: [ "main" ]
 
 jobs:
-  update-repo:
+  sync-subtrees:
     runs-on: ubuntu-latest
-
-    permissions:
-      # Give the default GITHUB_TOKEN write permission to commit and push the
-      # added or changed files to the repository.
-      contents: write
-
     steps:
-    - name: Checkout source
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    - name: Set up Git
-      run: |
-        git config --global user.name "${{ secrets.GIT_USERNAME }}"
-        git config --global user.email "${{ secrets.GIT_EMAIL }}"
+      - name: Set up Git
+        run: |
+          git config --global user.name "${{ secrets.GIT_USERNAME }}"
+          git config --global user.email "${{ secrets.GIT_EMAIL }}"
+  
 
-    - name: Make the script executable
-      run: chmod +x update_repo.sh
+      - name: Check if URLs file exists
+        run: |
+          if [ ! -f "onos_links.txt" ]; then
+            echo "Error: URLs file not found: onos_links.txt"
+            exit 1
+          fi
 
-    - name: Run update_repo.sh
-      run: ./update_repo.sh onos  # Change 'osc' to 'onos' or 'aic' as needed
+      - name: Process Git Subtrees
+        run: |
+          while IFS= read -r url; do
+            local_dir=$(basename "$url" .git)
 
-        # Commit all changed files back to the repository
-    - uses: stefanzweifel/git-auto-commit-action@v5
+            if [ -d "$local_dir" ]; then
+              echo "Updating subtree for URL: $url"
+              git subtree pull --prefix "$local_dir" "$url" master --squash
+            else
+              echo "Adding new subtree for URL: $url"
+              git subtree add --prefix "$local_dir" "$url" master --squash
+            fi
 
-
+            echo "Pushing subtree changes for URL: $url"
+            git subtree push --prefix "$local_dir" "$url" master
+          done < onos_links.txt
     
   Grype-Scan:
-    needs: update-repo
+    needs: sync-subtrees
     permissions:
       contents: read # for actions/checkout to fetch code
       security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
